### ISSUE TITLE
Unable to receive any updates

### ISSUE THREAD

**Issue by jeenjit** [lizzzcai/bbdc-booking-bot#1]
xxx bbdc-booking-bot % python3 main.py
'status'
'status'
'status'

Despite running it, i was unable to receive updates, any idea why

**Comment by lizzzcai** [comment]
Hi @jeenjit , the bot was developed based on the old bbdc login page: `https://info.bbdc.sg/members-login/` however I checked that they have developed a new page: `https://booking.bbdc.sg/`, and most likely the layout of the website is changed as well. 

In this case, the bot is no longer working with the new login page. You can try to update the [logic](https://github.com/lizzzcai/bbdc-booking-bot/blob/main/app.py#L35-L124) here to make it work with the new system.
